# Generated by Django 2.2 on 2020-10-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='posts',
            name='text',
            field=models.TextField(),
        ),
    ]
